export const ROUTE_TOKENS = {
  AUTH_PATH: '',
  LOGIN: 'login',
  REGISTER: 'register',
  PASSWORD_RECOVERY: 'password-recovery',
  CLIENT_PATH: '',
  CLIENT_HOME: 'inicio',
  DAP: 'depositos-a-plazo',
  DAP_DETAIL: ':id',
  NEW_DAP: 'nuevo-deposito',
  PROFILE: 'perfil',
  ADMIN_PATH: '',
  ADMIN_HOME: 'admin',
  ADMIN_CLIENTS: 'clientes',
}